server:
  port: 8084

spring:
  application:
    name: clearing-settlement-engine

  threads:
    virtual:
      enabled: true

  kafka:
    bootstrap-servers: localhost:9092
    streams:
      application-id: clearing-engine-app
      properties:
        default.key.serde: org.apache.kafka.common.serialization.Serdes$StringSerde
        default.value.serde: io.confluent.kafka.streams.serdes.avro.SpecificAvroSerde
        schema.registry.url: http://localhost:8081